todos/config/routes.rb
Rails.application.routes.draw do
  get 'home/todos'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

todos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

todos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

todos/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def todos
    @todos = TblTodo.all
  end
end

todos/app/helpers/application_helper.rb
module ApplicationHelper
end

todos/app/helpers/home_helper.rb
module HomeHelper
end

todos/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <%= link_to "Navbar", root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to 'Todos', home_todos_path, class:'nav-link' %>
                </li>
            </ul>
        </div>
    </div>
</nav>

todos/app/views/home/index.html.erb
<h1>Hello World</h1>

todos/app/views/home/todos.html.erb
<div class="container_todos">
    <div class="header_todos">
        <h2>My Todos</h2>
    </div>
    <div class="body_todos">
        <div class="add_todos_content">
            <%= render 'form', todo: @todo %>           
        </div>
    </div>
    <ul>
        <% @todos.each do |todo| %>
            <li><%= todo.todos_content %></li>
        <% end %>
    </ul>
</div>

todos/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title>Ruby App</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>